/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CreditNotesRouteImport } from './routes/credit-notes'
import { Route as BankRecRouteImport } from './routes/bank-rec'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditNotesRoute = CreditNotesRouteImport.update({
  id: '/credit-notes',
  path: '/credit-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRecRoute = BankRecRouteImport.update({
  id: '/bank-rec',
  path: '/bank-rec',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/bank-rec': typeof BankRecRoute
  '/credit-notes': typeof CreditNotesRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/ledger': typeof LedgerRoute
  '/notifications': typeof NotificationsRoute
  '/payroll': typeof PayrollRoute
  '/pos': typeof PosRoute
  '/procurement': typeof ProcurementRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/bank-rec': typeof BankRecRoute
  '/credit-notes': typeof CreditNotesRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/ledger': typeof LedgerRoute
  '/notifications': typeof NotificationsRoute
  '/payroll': typeof PayrollRoute
  '/pos': typeof PosRoute
  '/procurement': typeof ProcurementRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/bank-rec': typeof BankRecRoute
  '/credit-notes': typeof CreditNotesRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/ledger': typeof LedgerRoute
  '/notifications': typeof NotificationsRoute
  '/payroll': typeof PayrollRoute
  '/pos': typeof PosRoute
  '/procurement': typeof ProcurementRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/approvals'
    | '/audit'
    | '/bank-rec'
    | '/credit-notes'
    | '/customers'
    | '/inventory'
    | '/invoices'
    | '/ledger'
    | '/notifications'
    | '/payroll'
    | '/pos'
    | '/procurement'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/approvals'
    | '/audit'
    | '/bank-rec'
    | '/credit-notes'
    | '/customers'
    | '/inventory'
    | '/invoices'
    | '/ledger'
    | '/notifications'
    | '/payroll'
    | '/pos'
    | '/procurement'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/approvals'
    | '/audit'
    | '/bank-rec'
    | '/credit-notes'
    | '/customers'
    | '/inventory'
    | '/invoices'
    | '/ledger'
    | '/notifications'
    | '/payroll'
    | '/pos'
    | '/procurement'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  BankRecRoute: typeof BankRecRoute
  CreditNotesRoute: typeof CreditNotesRoute
  CustomersRoute: typeof CustomersRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  LedgerRoute: typeof LedgerRoute
  NotificationsRoute: typeof NotificationsRoute
  PayrollRoute: typeof PayrollRoute
  PosRoute: typeof PosRoute
  ProcurementRoute: typeof ProcurementRoute
  QuotationsRoute: typeof QuotationsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-notes': {
      id: '/credit-notes'
      path: '/credit-notes'
      fullPath: '/credit-notes'
      preLoaderRoute: typeof CreditNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-rec': {
      id: '/bank-rec'
      path: '/bank-rec'
      fullPath: '/bank-rec'
      preLoaderRoute: typeof BankRecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  BankRecRoute: BankRecRoute,
  CreditNotesRoute: CreditNotesRoute,
  CustomersRoute: CustomersRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  LedgerRoute: LedgerRoute,
  NotificationsRoute: NotificationsRoute,
  PayrollRoute: PayrollRoute,
  PosRoute: PosRoute,
  ProcurementRoute: ProcurementRoute,
  QuotationsRoute: QuotationsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
